import type { Metadata } from "next";
import { Inter, Bricolage_Grotesque } from "next/font/google";

import Header from "./components/Header";
import Footer from "./components/Footer";

import "primereact/resources/primereact.min.css";
import "primereact/resources/themes/bootstrap4-light-blue/theme.css"; 
import "remixicon/fonts/remixicon.css";
import "./globals.css";

const inter = Inter({ weight: ['300', '400', '500', '600', '700'], subsets: ["latin-ext"] });
const bricolage = Bricolage_Grotesque({ weight: ['300', '400', '500', '600', '700'], subsets: ["latin-ext"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en">
            <body className={bricolage.className}>
                <div className="max-w-[1400px] w-full min-h-screen m-auto flex flex-col items-center justify-center px-6 py-10 global-container">
                    <Header />
                    {children}
                    <Footer />
                </div>
            </body>
        </html>
    );
}
